feat: Account bootstrapping [DEV-3051]
cheqd/credential-service pull request #306
Opened 2023-07-26 14:25 UTC by anikitinDSR

- Add CredentialAccount creating if it's not created yet
- Add default role assigning if the list of roles is empty
- Add token populating if there are absent or not enough even for DID creation

2023-08-08 11:08 UTC, DaevMithran requested changes
Looks good, requested to move cosmjs functions entirely to sdk utils

2023-08-08 11:08 UTC, DaevMithran commented on src/controllers/customer.ts
> +    public static async checkBalance(address: string, network = NetworkType.Testnet) {
@anikitinDSR It's better to move this as a util function to our sdk. Even the getCosmosAccount. As these functions can be resused and can be managed easily when there are breaking changes in cosmjs

2023-08-08 11:08 UTC, DaevMithran commented on src/services/customer.ts
> +        const address = getCosmosAccount(kid)
getCosmosAccount should be move to sdk util as well

2023-08-09 07:00 UTC, abdulla-ashurov requested changes

2023-08-10 09:24 UTC, DaevMithran approved these changes

2023-08-10 09:42 UTC, abdulla-ashurov approved these changes

2023-08-10 09:42 UTC, merged