fix: Fix error handling on tracking operations [DEV-3494]
cheqd/credential-service pull request #461
Opened 2024-01-05 13:19 UTC by DaevMithran

2024-01-05 13:19 UTC, ankurdotb commented
Task linked: [DEV-3494 Make response bodies in predictable format](https://app.clickup.com/t/6600954/DEV-3494)

2024-01-09 16:30 UTC, anikitinDSR reviewed
Seems like this PR includes part of this PR:
https://github.com/cheqd/credential-service/pull/454
which is not related to tracking resource fix.
Let's merge https://github.com/cheqd/credential-service/pull/454 first and continue with tracking fix after.

2024-01-09 17:08 UTC, anikitinDSR reviewed
In general, removing result checking and sending 500 error looks fine

2024-01-11 11:45 UTC, anikitinDSR requested changes

2024-01-11 11:45 UTC, anikitinDSR commented on src/controllers/credential-status.ts
> +				return response.status(StatusCodes.OK).json({
I think it's not needed, cause in case of success  next line will be called and make the same action

2024-01-11 11:45 UTC, anikitinDSR commented on src/controllers/credential-status.ts
> +				return response.status(StatusCodes.OK).json({ ...formatted });
the same

2024-01-11 11:45 UTC, anikitinDSR commented on src/controllers/credentials.ts
> +				return response.status(StatusCodes.OK).json(result);
the same

2024-01-11 11:45 UTC, anikitinDSR commented on src/controllers/credentials.ts
> +				return response.status(StatusCodes.OK).json(result);
the same

2024-01-11 12:12 UTC, anikitinDSR approved these changes

2024-01-11 12:58 UTC, merged