Dev 3848
cheqd/credential-service pull request #522
Opened 2024-04-16 20:39 UTC by lampkin-diet

2024-04-16 20:39 UTC, ankurdotb commented
Task linked: [DEV-3848 Implement organisation details endpoints in customer table and build API](https://app.clickup.com/t/6600954/DEV-3848)

2024-04-17 04:46 UTC, DaevMithran requested changes

2024-04-17 04:46 UTC, DaevMithran commented on src/controllers/admin/organisation.ts
> +			isString().
Better to use `isEmail` here

2024-04-17 04:46 UTC, DaevMithran commented on src/controllers/admin/organisation.ts
> +			if (!customer || !paymentAccount) {
```suggestion
			if (!customer || paymentAccount.length === 0) {
```

2024-04-17 04:46 UTC, DaevMithran commented on src/controllers/admin/organisation.ts
> +			if (!customer || !paymentAccount) {
```suggestion
			if (!customer || paymentAccount.length === 0) {
```

2024-04-17 16:19 UTC, ankurdotb approved these changes

2024-04-17 16:27 UTC, merged